group: travis_lts

env:
  global:
    TERM=dumb

language: java
jdk: oraclejdk8

install: true

script:
  - bash ./mvnw clean package -U -f ./maven-producer/pom.xml -s maven-producer/settings.xml-default
  - bash ./mvnw clean package -U -f ./maven-consumer/pom.xml
  - java -jar ./maven-consumer/target/*-all.jar

cache:
  directories:
    - $HOME/.m2
