group: travis_lts

env:
  global:
    TERM=dumb

language: java
jdk: oraclejdk8

install: true

script:
  #- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  #- stop_any 5432 5672 27017 8080

  - bash mvnw clean package -U

cache:
  directories:
    - $HOME/.m2
